import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header";

const montserrat = Montserrat({ subsets: ["latin"], weight:['400', '500', '600', '700', '800','900','300','100', '200'] });

export const metadata: Metadata = {
  title: "WebX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header/>
        {children}
        </body>
    </html>
  );
}
